---
spring:
  jpa:
    properties:
      hibernate:
        # MySQL8に対応するDialectを設定
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.tool.schema.internal]": DEBUG
    "[org.flywaydb]": DEBUG 

management:
  endpoints:
    web:
      exposure:
        # 公開したいエンドポイントをカンマ区切りで指定
        include: health, metrics, prometheus, env, loggers, info, mappings
      base-path: /actuator
  endpoint:
    mappings:
      access: unrestricted
  metrics:
    enable:
      # 全メトリクスをデフォルトで有効化（必要に応じて個別指定も可能）
      all: true
