spring:
   datasource:
    url: jdbc:mysql://localhost:3306/tododb?useSSL=false&serverTimezone=UTC
    username: root
    password: dsM3kwHa
    driver-class-name: com.mysql.cj.jdbc.Driver
  
   security:
    user:
      name: ${ACTUATOR_USER:admin}          # 環境変数 or デフォルト
      password: ${ACTUATOR_PASSWORD:secret}

   jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: never
