---
spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: ${ACTUATOR_USER:admin} # 環境変数 or デフォルト
      password: ${ACTUATOR_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: never
