spring:
  application:
    name: todo-api
  profiles:
    active: dev    # デフォルトで dev プロファイルを有効にする
  datasource:
    # この設定はすべてのプロファイルで有効
    driver-class-name: org.h2.Driver
    username: sa
    password:

springdoc:
  api-docs:
    path: /v3/api-docs           # （必要なら）変更可能
  swagger-ui:
    path: /swagger-ui.html       # UI の起動パス
    operationsSorter: method     # GET→POST→…の順にソート  
