spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}   # MySQLのJDBC URL
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQLドライバーの指定
  jpa:
    hibernate:
      ddl-auto: update  # データベーススキーマの更新方法（適宜設定）
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   # MySQL8に対応するDialectを設定
  
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.tool.schema.internal]": DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, env, loggers   # 公開したいエンドポイントをカンマ区切りで指定
  metrics:
    enable:
      all: true    # 全メトリクスをデフォルトで有効化（必要に応じて個別指定も可能）
  