spring:
  application:
    name: todo-api
  profiles:
    active: dev    # デフォルトで dev プロファイルを有効にする
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}    # Dockerのコンテナ内でのMySQL接続URL
    username: ${SPRING_DATASOURCE_USERNAME} 
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # テーブルが自動で作成される設定
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs           # （必要なら）変更可能
  swagger-ui:
    path: /swagger-ui.html       # UI の起動パス
    operationsSorter: method     # GET→POST→…の順にソート  
